//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Console1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class D3Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new D3Entities object using the connection string found in the 'D3Entities' section of the application configuration file.
        /// </summary>
        public D3Entities() : base("name=D3Entities", "D3Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new D3Entities object.
        /// </summary>
        public D3Entities(string connectionString) : base(connectionString, "D3Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new D3Entities object.
        /// </summary>
        public D3Entities(EntityConnection connection) : base(connection, "D3Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CurrentDayPickups> CurrentDayPickups1
        {
            get
            {
                if ((_CurrentDayPickups1 == null))
                {
                    _CurrentDayPickups1 = base.CreateObjectSet<CurrentDayPickups>("CurrentDayPickups1");
                }
                return _CurrentDayPickups1;
            }
        }
        private ObjectSet<CurrentDayPickups> _CurrentDayPickups1;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CurrentDayRoutes> CurrentDayRoutes1
        {
            get
            {
                if ((_CurrentDayRoutes1 == null))
                {
                    _CurrentDayRoutes1 = base.CreateObjectSet<CurrentDayRoutes>("CurrentDayRoutes1");
                }
                return _CurrentDayRoutes1;
            }
        }
        private ObjectSet<CurrentDayRoutes> _CurrentDayRoutes1;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Customers> Customers
        {
            get
            {
                if ((_Customers == null))
                {
                    _Customers = base.CreateObjectSet<Customers>("Customers");
                }
                return _Customers;
            }
        }
        private ObjectSet<Customers> _Customers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Drivers> Drivers
        {
            get
            {
                if ((_Drivers == null))
                {
                    _Drivers = base.CreateObjectSet<Drivers>("Drivers");
                }
                return _Drivers;
            }
        }
        private ObjectSet<Drivers> _Drivers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ArchivedPickups> ArchivedPickups
        {
            get
            {
                if ((_ArchivedPickups == null))
                {
                    _ArchivedPickups = base.CreateObjectSet<ArchivedPickups>("ArchivedPickups");
                }
                return _ArchivedPickups;
            }
        }
        private ObjectSet<ArchivedPickups> _ArchivedPickups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pickups> Pickups1
        {
            get
            {
                if ((_Pickups1 == null))
                {
                    _Pickups1 = base.CreateObjectSet<Pickups>("Pickups1");
                }
                return _Pickups1;
            }
        }
        private ObjectSet<Pickups> _Pickups1;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PostedMessages> PostedMessages
        {
            get
            {
                if ((_PostedMessages == null))
                {
                    _PostedMessages = base.CreateObjectSet<PostedMessages>("PostedMessages");
                }
                return _PostedMessages;
            }
        }
        private ObjectSet<PostedMessages> _PostedMessages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Routes> Routes
        {
            get
            {
                if ((_Routes == null))
                {
                    _Routes = base.CreateObjectSet<Routes>("Routes");
                }
                return _Routes;
            }
        }
        private ObjectSet<Routes> _Routes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CurrentDayPickups1 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCurrentDayPickups1(CurrentDayPickups currentDayPickups)
        {
            base.AddObject("CurrentDayPickups1", currentDayPickups);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CurrentDayRoutes1 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCurrentDayRoutes1(CurrentDayRoutes currentDayRoutes)
        {
            base.AddObject("CurrentDayRoutes1", currentDayRoutes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomers(Customers customers)
        {
            base.AddObject("Customers", customers);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Drivers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDrivers(Drivers drivers)
        {
            base.AddObject("Drivers", drivers);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ArchivedPickups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArchivedPickups(ArchivedPickups archivedPickups)
        {
            base.AddObject("ArchivedPickups", archivedPickups);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pickups1 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPickups1(Pickups pickups)
        {
            base.AddObject("Pickups1", pickups);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PostedMessages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPostedMessages(PostedMessages postedMessages)
        {
            base.AddObject("PostedMessages", postedMessages);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Routes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoutes(Routes routes)
        {
            base.AddObject("Routes", routes);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="D3Model", Name="ArchivedPickups")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ArchivedPickups : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ArchivedPickups object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static ArchivedPickups CreateArchivedPickups(global::System.Int32 id)
        {
            ArchivedPickups archivedPickups = new ArchivedPickups();
            archivedPickups.Id = id;
            return archivedPickups;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DefaultRouteID
        {
            get
            {
                return _DefaultRouteID;
            }
            set
            {
                OnDefaultRouteIDChanging(value);
                ReportPropertyChanging("DefaultRouteID");
                _DefaultRouteID = StructuralObject.SetValidValue(value, true, "DefaultRouteID");
                ReportPropertyChanged("DefaultRouteID");
                OnDefaultRouteIDChanged();
            }
        }
        private global::System.String _DefaultRouteID;
        partial void OnDefaultRouteIDChanging(global::System.String value);
        partial void OnDefaultRouteIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PickupDate
        {
            get
            {
                return _PickupDate;
            }
            set
            {
                OnPickupDateChanging(value);
                ReportPropertyChanging("PickupDate");
                _PickupDate = StructuralObject.SetValidValue(value, "PickupDate");
                ReportPropertyChanged("PickupDate");
                OnPickupDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PickupDate;
        partial void OnPickupDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPickupDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerKey
        {
            get
            {
                return _CustomerKey;
            }
            set
            {
                OnCustomerKeyChanging(value);
                ReportPropertyChanging("CustomerKey");
                _CustomerKey = StructuralObject.SetValidValue(value, true, "CustomerKey");
                ReportPropertyChanged("CustomerKey");
                OnCustomerKeyChanged();
            }
        }
        private global::System.String _CustomerKey;
        partial void OnCustomerKeyChanging(global::System.String value);
        partial void OnCustomerKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DriverName
        {
            get
            {
                return _DriverName;
            }
            set
            {
                OnDriverNameChanging(value);
                ReportPropertyChanging("DriverName");
                _DriverName = StructuralObject.SetValidValue(value, true, "DriverName");
                ReportPropertyChanged("DriverName");
                OnDriverNameChanged();
            }
        }
        private global::System.String _DriverName;
        partial void OnDriverNameChanging(global::System.String value);
        partial void OnDriverNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DriverMessage
        {
            get
            {
                return _DriverMessage;
            }
            set
            {
                OnDriverMessageChanging(value);
                ReportPropertyChanging("DriverMessage");
                _DriverMessage = StructuralObject.SetValidValue(value, true, "DriverMessage");
                ReportPropertyChanged("DriverMessage");
                OnDriverMessageChanged();
            }
        }
        private global::System.String _DriverMessage;
        partial void OnDriverMessageChanging(global::System.String value);
        partial void OnDriverMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RouteName
        {
            get
            {
                return _RouteName;
            }
            set
            {
                OnRouteNameChanging(value);
                ReportPropertyChanging("RouteName");
                _RouteName = StructuralObject.SetValidValue(value, true, "RouteName");
                ReportPropertyChanged("RouteName");
                OnRouteNameChanged();
            }
        }
        private global::System.String _RouteName;
        partial void OnRouteNameChanging(global::System.String value);
        partial void OnRouteNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                OnCustomerNameChanging(value);
                ReportPropertyChanging("CustomerName");
                _CustomerName = StructuralObject.SetValidValue(value, true, "CustomerName");
                ReportPropertyChanged("CustomerName");
                OnCustomerNameChanged();
            }
        }
        private global::System.String _CustomerName;
        partial void OnCustomerNameChanging(global::System.String value);
        partial void OnCustomerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true, "Comment");
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Dispatched
        {
            get
            {
                return _Dispatched;
            }
            set
            {
                OnDispatchedChanging(value);
                ReportPropertyChanging("Dispatched");
                _Dispatched = StructuralObject.SetValidValue(value, "Dispatched");
                ReportPropertyChanged("Dispatched");
                OnDispatchedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Dispatched;
        partial void OnDispatchedChanging(Nullable<global::System.Boolean> value);
        partial void OnDispatchedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DispatchTime
        {
            get
            {
                return _DispatchTime;
            }
            set
            {
                OnDispatchTimeChanging(value);
                ReportPropertyChanging("DispatchTime");
                _DispatchTime = StructuralObject.SetValidValue(value, "DispatchTime");
                ReportPropertyChanged("DispatchTime");
                OnDispatchTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _DispatchTime;
        partial void OnDispatchTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnDispatchTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Deleted
        {
            get
            {
                return _Deleted;
            }
            set
            {
                OnDeletedChanging(value);
                ReportPropertyChanging("Deleted");
                _Deleted = StructuralObject.SetValidValue(value, "Deleted");
                ReportPropertyChanged("Deleted");
                OnDeletedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Deleted;
        partial void OnDeletedChanging(Nullable<global::System.Boolean> value);
        partial void OnDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true, "Notes");
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="D3Model", Name="CurrentDayPickups")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CurrentDayPickups : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CurrentDayPickups object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="isDispatched">Initial value of the IsDispatched property.</param>
        public static CurrentDayPickups CreateCurrentDayPickups(global::System.Int32 id, global::System.Boolean isDispatched)
        {
            CurrentDayPickups currentDayPickups = new CurrentDayPickups();
            currentDayPickups.Id = id;
            currentDayPickups.IsDispatched = isDispatched;
            return currentDayPickups;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RouteId
        {
            get
            {
                return _RouteId;
            }
            set
            {
                OnRouteIdChanging(value);
                ReportPropertyChanging("RouteId");
                _RouteId = StructuralObject.SetValidValue(value, true, "RouteId");
                ReportPropertyChanged("RouteId");
                OnRouteIdChanged();
            }
        }
        private global::System.String _RouteId;
        partial void OnRouteIdChanging(global::System.String value);
        partial void OnRouteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RouteName
        {
            get
            {
                return _RouteName;
            }
            set
            {
                OnRouteNameChanging(value);
                ReportPropertyChanging("RouteName");
                _RouteName = StructuralObject.SetValidValue(value, true, "RouteName");
                ReportPropertyChanged("RouteName");
                OnRouteNameChanged();
            }
        }
        private global::System.String _RouteName;
        partial void OnRouteNameChanging(global::System.String value);
        partial void OnRouteNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PreviousRouteId
        {
            get
            {
                return _PreviousRouteId;
            }
            set
            {
                OnPreviousRouteIdChanging(value);
                ReportPropertyChanging("PreviousRouteId");
                _PreviousRouteId = StructuralObject.SetValidValue(value, true, "PreviousRouteId");
                ReportPropertyChanged("PreviousRouteId");
                OnPreviousRouteIdChanged();
            }
        }
        private global::System.String _PreviousRouteId;
        partial void OnPreviousRouteIdChanging(global::System.String value);
        partial void OnPreviousRouteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PickupDate
        {
            get
            {
                return _PickupDate;
            }
            set
            {
                OnPickupDateChanging(value);
                ReportPropertyChanging("PickupDate");
                _PickupDate = StructuralObject.SetValidValue(value, "PickupDate");
                ReportPropertyChanged("PickupDate");
                OnPickupDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PickupDate;
        partial void OnPickupDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPickupDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerKey
        {
            get
            {
                return _CustomerKey;
            }
            set
            {
                OnCustomerKeyChanging(value);
                ReportPropertyChanging("CustomerKey");
                _CustomerKey = StructuralObject.SetValidValue(value, true, "CustomerKey");
                ReportPropertyChanged("CustomerKey");
                OnCustomerKeyChanged();
            }
        }
        private global::System.String _CustomerKey;
        partial void OnCustomerKeyChanging(global::System.String value);
        partial void OnCustomerKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                OnCustomerNameChanging(value);
                ReportPropertyChanging("CustomerName");
                _CustomerName = StructuralObject.SetValidValue(value, true, "CustomerName");
                ReportPropertyChanged("CustomerName");
                OnCustomerNameChanged();
            }
        }
        private global::System.String _CustomerName;
        partial void OnCustomerNameChanging(global::System.String value);
        partial void OnCustomerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DriverName
        {
            get
            {
                return _DriverName;
            }
            set
            {
                OnDriverNameChanging(value);
                ReportPropertyChanging("DriverName");
                _DriverName = StructuralObject.SetValidValue(value, true, "DriverName");
                ReportPropertyChanged("DriverName");
                OnDriverNameChanged();
            }
        }
        private global::System.String _DriverName;
        partial void OnDriverNameChanging(global::System.String value);
        partial void OnDriverNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DriverMessage
        {
            get
            {
                return _DriverMessage;
            }
            set
            {
                OnDriverMessageChanging(value);
                ReportPropertyChanging("DriverMessage");
                _DriverMessage = StructuralObject.SetValidValue(value, true, "DriverMessage");
                ReportPropertyChanged("DriverMessage");
                OnDriverMessageChanged();
            }
        }
        private global::System.String _DriverMessage;
        partial void OnDriverMessageChanging(global::System.String value);
        partial void OnDriverMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true, "Comment");
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsDispatched
        {
            get
            {
                return _IsDispatched;
            }
            set
            {
                OnIsDispatchedChanging(value);
                ReportPropertyChanging("IsDispatched");
                _IsDispatched = StructuralObject.SetValidValue(value, "IsDispatched");
                ReportPropertyChanged("IsDispatched");
                OnIsDispatchedChanged();
            }
        }
        private global::System.Boolean _IsDispatched;
        partial void OnIsDispatchedChanging(global::System.Boolean value);
        partial void OnIsDispatchedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DispatchTime
        {
            get
            {
                return _DispatchTime;
            }
            set
            {
                OnDispatchTimeChanging(value);
                ReportPropertyChanging("DispatchTime");
                _DispatchTime = StructuralObject.SetValidValue(value, "DispatchTime");
                ReportPropertyChanged("DispatchTime");
                OnDispatchTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _DispatchTime;
        partial void OnDispatchTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnDispatchTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true, "Notes");
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="D3Model", Name="CurrentDayRoutes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CurrentDayRoutes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CurrentDayRoutes object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static CurrentDayRoutes CreateCurrentDayRoutes(global::System.Int32 id)
        {
            CurrentDayRoutes currentDayRoutes = new CurrentDayRoutes();
            currentDayRoutes.Id = id;
            return currentDayRoutes;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RouteKey
        {
            get
            {
                return _RouteKey;
            }
            set
            {
                OnRouteKeyChanging(value);
                ReportPropertyChanging("RouteKey");
                _RouteKey = StructuralObject.SetValidValue(value, true, "RouteKey");
                ReportPropertyChanged("RouteKey");
                OnRouteKeyChanged();
            }
        }
        private global::System.String _RouteKey;
        partial void OnRouteKeyChanging(global::System.String value);
        partial void OnRouteKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RouteName
        {
            get
            {
                return _RouteName;
            }
            set
            {
                OnRouteNameChanging(value);
                ReportPropertyChanging("RouteName");
                _RouteName = StructuralObject.SetValidValue(value, true, "RouteName");
                ReportPropertyChanged("RouteName");
                OnRouteNameChanged();
            }
        }
        private global::System.String _RouteName;
        partial void OnRouteNameChanging(global::System.String value);
        partial void OnRouteNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DriverId
        {
            get
            {
                return _DriverId;
            }
            set
            {
                OnDriverIdChanging(value);
                ReportPropertyChanging("DriverId");
                _DriverId = StructuralObject.SetValidValue(value, true, "DriverId");
                ReportPropertyChanged("DriverId");
                OnDriverIdChanged();
            }
        }
        private global::System.String _DriverId;
        partial void OnDriverIdChanging(global::System.String value);
        partial void OnDriverIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DriverName
        {
            get
            {
                return _DriverName;
            }
            set
            {
                OnDriverNameChanging(value);
                ReportPropertyChanging("DriverName");
                _DriverName = StructuralObject.SetValidValue(value, true, "DriverName");
                ReportPropertyChanged("DriverName");
                OnDriverNameChanged();
            }
        }
        private global::System.String _DriverName;
        partial void OnDriverNameChanging(global::System.String value);
        partial void OnDriverNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DriverMessage
        {
            get
            {
                return _DriverMessage;
            }
            set
            {
                OnDriverMessageChanging(value);
                ReportPropertyChanging("DriverMessage");
                _DriverMessage = StructuralObject.SetValidValue(value, true, "DriverMessage");
                ReportPropertyChanged("DriverMessage");
                OnDriverMessageChanged();
            }
        }
        private global::System.String _DriverMessage;
        partial void OnDriverMessageChanging(global::System.String value);
        partial void OnDriverMessageChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="D3Model", Name="Customers")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customers : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Customers object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Customers CreateCustomers(global::System.Int32 id)
        {
            Customers customers = new Customers();
            customers.Id = id;
            return customers;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerKey
        {
            get
            {
                return _CustomerKey;
            }
            set
            {
                OnCustomerKeyChanging(value);
                ReportPropertyChanging("CustomerKey");
                _CustomerKey = StructuralObject.SetValidValue(value, true, "CustomerKey");
                ReportPropertyChanged("CustomerKey");
                OnCustomerKeyChanged();
            }
        }
        private global::System.String _CustomerKey;
        partial void OnCustomerKeyChanging(global::System.String value);
        partial void OnCustomerKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                OnCustomerNameChanging(value);
                ReportPropertyChanging("CustomerName");
                _CustomerName = StructuralObject.SetValidValue(value, true, "CustomerName");
                ReportPropertyChanged("CustomerName");
                OnCustomerNameChanged();
            }
        }
        private global::System.String _CustomerName;
        partial void OnCustomerNameChanging(global::System.String value);
        partial void OnCustomerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address1
        {
            get
            {
                return _Address1;
            }
            set
            {
                OnAddress1Changing(value);
                ReportPropertyChanging("Address1");
                _Address1 = StructuralObject.SetValidValue(value, true, "Address1");
                ReportPropertyChanged("Address1");
                OnAddress1Changed();
            }
        }
        private global::System.String _Address1;
        partial void OnAddress1Changing(global::System.String value);
        partial void OnAddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true, "City");
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true, "State");
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true, "Phone");
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contact
        {
            get
            {
                return _Contact;
            }
            set
            {
                OnContactChanging(value);
                ReportPropertyChanging("Contact");
                _Contact = StructuralObject.SetValidValue(value, true, "Contact");
                ReportPropertyChanged("Contact");
                OnContactChanged();
            }
        }
        private global::System.String _Contact;
        partial void OnContactChanging(global::System.String value);
        partial void OnContactChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClosingTime
        {
            get
            {
                return _ClosingTime;
            }
            set
            {
                OnClosingTimeChanging(value);
                ReportPropertyChanging("ClosingTime");
                _ClosingTime = StructuralObject.SetValidValue(value, true, "ClosingTime");
                ReportPropertyChanged("ClosingTime");
                OnClosingTimeChanged();
            }
        }
        private global::System.String _ClosingTime;
        partial void OnClosingTimeChanging(global::System.String value);
        partial void OnClosingTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true, "Comment");
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DefaultRouteId
        {
            get
            {
                return _DefaultRouteId;
            }
            set
            {
                OnDefaultRouteIdChanging(value);
                ReportPropertyChanging("DefaultRouteId");
                _DefaultRouteId = StructuralObject.SetValidValue(value, true, "DefaultRouteId");
                ReportPropertyChanged("DefaultRouteId");
                OnDefaultRouteIdChanged();
            }
        }
        private global::System.String _DefaultRouteId;
        partial void OnDefaultRouteIdChanging(global::System.String value);
        partial void OnDefaultRouteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InfoString
        {
            get
            {
                return _InfoString;
            }
            set
            {
                OnInfoStringChanging(value);
                ReportPropertyChanging("InfoString");
                _InfoString = StructuralObject.SetValidValue(value, true, "InfoString");
                ReportPropertyChanged("InfoString");
                OnInfoStringChanged();
            }
        }
        private global::System.String _InfoString;
        partial void OnInfoStringChanging(global::System.String value);
        partial void OnInfoStringChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="D3Model", Name="Drivers")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Drivers : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Drivers object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Drivers CreateDrivers(global::System.Int32 id)
        {
            Drivers drivers = new Drivers();
            drivers.Id = id;
            return drivers;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DriverKey
        {
            get
            {
                return _DriverKey;
            }
            set
            {
                OnDriverKeyChanging(value);
                ReportPropertyChanging("DriverKey");
                _DriverKey = StructuralObject.SetValidValue(value, true, "DriverKey");
                ReportPropertyChanged("DriverKey");
                OnDriverKeyChanged();
            }
        }
        private global::System.String _DriverKey;
        partial void OnDriverKeyChanging(global::System.String value);
        partial void OnDriverKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true, "LastName");
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true, "FirstName");
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MiddleInitial
        {
            get
            {
                return _MiddleInitial;
            }
            set
            {
                OnMiddleInitialChanging(value);
                ReportPropertyChanging("MiddleInitial");
                _MiddleInitial = StructuralObject.SetValidValue(value, true, "MiddleInitial");
                ReportPropertyChanged("MiddleInitial");
                OnMiddleInitialChanged();
            }
        }
        private global::System.String _MiddleInitial;
        partial void OnMiddleInitialChanging(global::System.String value);
        partial void OnMiddleInitialChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="D3Model", Name="Pickups")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pickups : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pickups object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Pickups CreatePickups(global::System.Int32 id)
        {
            Pickups pickups = new Pickups();
            pickups.Id = id;
            return pickups;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DefaultRouteId
        {
            get
            {
                return _DefaultRouteId;
            }
            set
            {
                OnDefaultRouteIdChanging(value);
                ReportPropertyChanging("DefaultRouteId");
                _DefaultRouteId = StructuralObject.SetValidValue(value, true, "DefaultRouteId");
                ReportPropertyChanged("DefaultRouteId");
                OnDefaultRouteIdChanged();
            }
        }
        private global::System.String _DefaultRouteId;
        partial void OnDefaultRouteIdChanging(global::System.String value);
        partial void OnDefaultRouteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PickupDate
        {
            get
            {
                return _PickupDate;
            }
            set
            {
                OnPickupDateChanging(value);
                ReportPropertyChanging("PickupDate");
                _PickupDate = StructuralObject.SetValidValue(value, "PickupDate");
                ReportPropertyChanged("PickupDate");
                OnPickupDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PickupDate;
        partial void OnPickupDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPickupDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerKey
        {
            get
            {
                return _CustomerKey;
            }
            set
            {
                OnCustomerKeyChanging(value);
                ReportPropertyChanging("CustomerKey");
                _CustomerKey = StructuralObject.SetValidValue(value, true, "CustomerKey");
                ReportPropertyChanged("CustomerKey");
                OnCustomerKeyChanged();
            }
        }
        private global::System.String _CustomerKey;
        partial void OnCustomerKeyChanging(global::System.String value);
        partial void OnCustomerKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DriverName
        {
            get
            {
                return _DriverName;
            }
            set
            {
                OnDriverNameChanging(value);
                ReportPropertyChanging("DriverName");
                _DriverName = StructuralObject.SetValidValue(value, true, "DriverName");
                ReportPropertyChanged("DriverName");
                OnDriverNameChanged();
            }
        }
        private global::System.String _DriverName;
        partial void OnDriverNameChanging(global::System.String value);
        partial void OnDriverNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RouteName
        {
            get
            {
                return _RouteName;
            }
            set
            {
                OnRouteNameChanging(value);
                ReportPropertyChanging("RouteName");
                _RouteName = StructuralObject.SetValidValue(value, true, "RouteName");
                ReportPropertyChanged("RouteName");
                OnRouteNameChanged();
            }
        }
        private global::System.String _RouteName;
        partial void OnRouteNameChanging(global::System.String value);
        partial void OnRouteNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                OnCustomerNameChanging(value);
                ReportPropertyChanging("CustomerName");
                _CustomerName = StructuralObject.SetValidValue(value, true, "CustomerName");
                ReportPropertyChanged("CustomerName");
                OnCustomerNameChanged();
            }
        }
        private global::System.String _CustomerName;
        partial void OnCustomerNameChanging(global::System.String value);
        partial void OnCustomerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true, "Comment");
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Monday
        {
            get
            {
                return _Monday;
            }
            set
            {
                OnMondayChanging(value);
                ReportPropertyChanging("Monday");
                _Monday = StructuralObject.SetValidValue(value, "Monday");
                ReportPropertyChanged("Monday");
                OnMondayChanged();
            }
        }
        private Nullable<global::System.Boolean> _Monday;
        partial void OnMondayChanging(Nullable<global::System.Boolean> value);
        partial void OnMondayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Tuesday
        {
            get
            {
                return _Tuesday;
            }
            set
            {
                OnTuesdayChanging(value);
                ReportPropertyChanging("Tuesday");
                _Tuesday = StructuralObject.SetValidValue(value, "Tuesday");
                ReportPropertyChanged("Tuesday");
                OnTuesdayChanged();
            }
        }
        private Nullable<global::System.Boolean> _Tuesday;
        partial void OnTuesdayChanging(Nullable<global::System.Boolean> value);
        partial void OnTuesdayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Wednesday
        {
            get
            {
                return _Wednesday;
            }
            set
            {
                OnWednesdayChanging(value);
                ReportPropertyChanging("Wednesday");
                _Wednesday = StructuralObject.SetValidValue(value, "Wednesday");
                ReportPropertyChanged("Wednesday");
                OnWednesdayChanged();
            }
        }
        private Nullable<global::System.Boolean> _Wednesday;
        partial void OnWednesdayChanging(Nullable<global::System.Boolean> value);
        partial void OnWednesdayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Thursday
        {
            get
            {
                return _Thursday;
            }
            set
            {
                OnThursdayChanging(value);
                ReportPropertyChanging("Thursday");
                _Thursday = StructuralObject.SetValidValue(value, "Thursday");
                ReportPropertyChanged("Thursday");
                OnThursdayChanged();
            }
        }
        private Nullable<global::System.Boolean> _Thursday;
        partial void OnThursdayChanging(Nullable<global::System.Boolean> value);
        partial void OnThursdayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Friday
        {
            get
            {
                return _Friday;
            }
            set
            {
                OnFridayChanging(value);
                ReportPropertyChanging("Friday");
                _Friday = StructuralObject.SetValidValue(value, "Friday");
                ReportPropertyChanged("Friday");
                OnFridayChanged();
            }
        }
        private Nullable<global::System.Boolean> _Friday;
        partial void OnFridayChanging(Nullable<global::System.Boolean> value);
        partial void OnFridayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Dispatched
        {
            get
            {
                return _Dispatched;
            }
            set
            {
                OnDispatchedChanging(value);
                ReportPropertyChanging("Dispatched");
                _Dispatched = StructuralObject.SetValidValue(value, "Dispatched");
                ReportPropertyChanged("Dispatched");
                OnDispatchedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Dispatched;
        partial void OnDispatchedChanging(Nullable<global::System.Boolean> value);
        partial void OnDispatchedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DispatchTime
        {
            get
            {
                return _DispatchTime;
            }
            set
            {
                OnDispatchTimeChanging(value);
                ReportPropertyChanging("DispatchTime");
                _DispatchTime = StructuralObject.SetValidValue(value, "DispatchTime");
                ReportPropertyChanged("DispatchTime");
                OnDispatchTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _DispatchTime;
        partial void OnDispatchTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnDispatchTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true, "Notes");
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="D3Model", Name="PostedMessages")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PostedMessages : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PostedMessages object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="isDragnDrop">Initial value of the isDragnDrop property.</param>
        public static PostedMessages CreatePostedMessages(global::System.Int32 id, global::System.Boolean isDragnDrop)
        {
            PostedMessages postedMessages = new PostedMessages();
            postedMessages.Id = id;
            postedMessages.isDragnDrop = isDragnDrop;
            return postedMessages;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DataType
        {
            get
            {
                return _DataType;
            }
            set
            {
                OnDataTypeChanging(value);
                ReportPropertyChanging("DataType");
                _DataType = StructuralObject.SetValidValue(value, true, "DataType");
                ReportPropertyChanged("DataType");
                OnDataTypeChanged();
            }
        }
        private global::System.String _DataType;
        partial void OnDataTypeChanging(global::System.String value);
        partial void OnDataTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Key
        {
            get
            {
                return _Key;
            }
            set
            {
                OnKeyChanging(value);
                ReportPropertyChanging("Key");
                _Key = StructuralObject.SetValidValue(value, "Key");
                ReportPropertyChanged("Key");
                OnKeyChanged();
            }
        }
        private Nullable<global::System.Int32> _Key;
        partial void OnKeyChanging(Nullable<global::System.Int32> value);
        partial void OnKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NumberofPendingUpdates
        {
            get
            {
                return _NumberofPendingUpdates;
            }
            set
            {
                OnNumberofPendingUpdatesChanging(value);
                ReportPropertyChanging("NumberofPendingUpdates");
                _NumberofPendingUpdates = StructuralObject.SetValidValue(value, "NumberofPendingUpdates");
                ReportPropertyChanged("NumberofPendingUpdates");
                OnNumberofPendingUpdatesChanged();
            }
        }
        private Nullable<global::System.Int32> _NumberofPendingUpdates;
        partial void OnNumberofPendingUpdatesChanging(Nullable<global::System.Int32> value);
        partial void OnNumberofPendingUpdatesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Originator
        {
            get
            {
                return _Originator;
            }
            set
            {
                OnOriginatorChanging(value);
                ReportPropertyChanging("Originator");
                _Originator = StructuralObject.SetValidValue(value, true, "Originator");
                ReportPropertyChanged("Originator");
                OnOriginatorChanged();
            }
        }
        private global::System.String _Originator;
        partial void OnOriginatorChanging(global::System.String value);
        partial void OnOriginatorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DefaultRouteId
        {
            get
            {
                return _DefaultRouteId;
            }
            set
            {
                OnDefaultRouteIdChanging(value);
                ReportPropertyChanging("DefaultRouteId");
                _DefaultRouteId = StructuralObject.SetValidValue(value, true, "DefaultRouteId");
                ReportPropertyChanged("DefaultRouteId");
                OnDefaultRouteIdChanged();
            }
        }
        private global::System.String _DefaultRouteId;
        partial void OnDefaultRouteIdChanging(global::System.String value);
        partial void OnDefaultRouteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PreviousRouteID
        {
            get
            {
                return _PreviousRouteID;
            }
            set
            {
                OnPreviousRouteIDChanging(value);
                ReportPropertyChanging("PreviousRouteID");
                _PreviousRouteID = StructuralObject.SetValidValue(value, true, "PreviousRouteID");
                ReportPropertyChanged("PreviousRouteID");
                OnPreviousRouteIDChanged();
            }
        }
        private global::System.String _PreviousRouteID;
        partial void OnPreviousRouteIDChanging(global::System.String value);
        partial void OnPreviousRouteIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isDragnDrop
        {
            get
            {
                return _isDragnDrop;
            }
            set
            {
                OnisDragnDropChanging(value);
                ReportPropertyChanging("isDragnDrop");
                _isDragnDrop = StructuralObject.SetValidValue(value, "isDragnDrop");
                ReportPropertyChanged("isDragnDrop");
                OnisDragnDropChanged();
            }
        }
        private global::System.Boolean _isDragnDrop;
        partial void OnisDragnDropChanging(global::System.Boolean value);
        partial void OnisDragnDropChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="D3Model", Name="Routes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Routes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Routes object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Routes CreateRoutes(global::System.Int32 id)
        {
            Routes routes = new Routes();
            routes.Id = id;
            return routes;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RouteKey
        {
            get
            {
                return _RouteKey;
            }
            set
            {
                OnRouteKeyChanging(value);
                ReportPropertyChanging("RouteKey");
                _RouteKey = StructuralObject.SetValidValue(value, true, "RouteKey");
                ReportPropertyChanged("RouteKey");
                OnRouteKeyChanged();
            }
        }
        private global::System.String _RouteKey;
        partial void OnRouteKeyChanging(global::System.String value);
        partial void OnRouteKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RouteName
        {
            get
            {
                return _RouteName;
            }
            set
            {
                OnRouteNameChanging(value);
                ReportPropertyChanging("RouteName");
                _RouteName = StructuralObject.SetValidValue(value, true, "RouteName");
                ReportPropertyChanged("RouteName");
                OnRouteNameChanged();
            }
        }
        private global::System.String _RouteName;
        partial void OnRouteNameChanging(global::System.String value);
        partial void OnRouteNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DriverId
        {
            get
            {
                return _DriverId;
            }
            set
            {
                OnDriverIdChanging(value);
                ReportPropertyChanging("DriverId");
                _DriverId = StructuralObject.SetValidValue(value, true, "DriverId");
                ReportPropertyChanged("DriverId");
                OnDriverIdChanged();
            }
        }
        private global::System.String _DriverId;
        partial void OnDriverIdChanging(global::System.String value);
        partial void OnDriverIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DriverMessage
        {
            get
            {
                return _DriverMessage;
            }
            set
            {
                OnDriverMessageChanging(value);
                ReportPropertyChanging("DriverMessage");
                _DriverMessage = StructuralObject.SetValidValue(value, true, "DriverMessage");
                ReportPropertyChanged("DriverMessage");
                OnDriverMessageChanged();
            }
        }
        private global::System.String _DriverMessage;
        partial void OnDriverMessageChanging(global::System.String value);
        partial void OnDriverMessageChanged();

        #endregion

    }

    #endregion

}
