//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drivers
    {
        public int Id { get; set; }
        public string DriverKey { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string DriverSyncID { get; set; }
        public string DriverCreatedBy { get; set; }
        public Nullable<System.DateTime> DriverCreatedTime { get; set; }
        public string DriverEditedBy { get; set; }
        public Nullable<System.DateTime> DriverEditedTime { get; set; }
        public Nullable<bool> DriverSent { get; set; }
        public Nullable<System.DateTime> DriverSentTime { get; set; }
        public Nullable<bool> DriverSendConfirmed { get; set; }
        public Nullable<System.DateTime> DriverReceivedTime { get; set; }
    
        public virtual CurrentDayRoute CurrentDayRoute { get; set; }
        public virtual Route2 Route2 { get; set; }
    }
}
